USE alx_book_store;

SELECT
    c.COLUMN_NAME,
    c.ORDINAL_POSITION,
    c.COLUMN_TYPE,
    c.IS_NULLABLE,
    c.COLUMN_DEFAULT,
    c.EXTRA,
    c.COLLATION_NAME,
    c.CHARACTER_SET_NAME
FROM INFORMATION_SCHEMA.COLUMNS AS c
WHERE c.TABLE_SCHEMA = 'alx_book_store'
  AND c.TABLE_NAME = 'Books'
ORDER BY c.ORDINAL_POSITION;

SELECT
    k.CONSTRAINT_NAME,
    k.COLUMN_NAME,
    k.REFERENCED_TABLE_NAME,
    k.REFERENCED_COLUMN_NAME
FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE AS k
WHERE k.TABLE_SCHEMA = 'alx_book_store'
  AND k.TABLE_NAME = 'Books'
ORDER BY k.CONSTRAINT_NAME, k.ORDINAL_POSITION;
